[package]
name = "youtube_downloader_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
rusty_ytdl = "0.7.0"
tokio = { version = "1.36.0", features = ["full"] }
futures = "0.3.30"
